# Generated by Django 5.2.3 on 2025-08-04 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("subjects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Degree",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="学位名称"
                    ),
                ),
                (
                    "remark",
                    models.TextField(blank=True, null=True, verbose_name="备注"),
                ),
            ],
            options={
                "verbose_name": "学位表",
                "verbose_name_plural": "学位表",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="学历名称"
                    ),
                ),
                (
                    "remark",
                    models.TextField(blank=True, null=True, verbose_name="备注"),
                ),
            ],
            options={
                "verbose_name": "学历表",
                "verbose_name_plural": "学历表",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="Gender",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="性别名称"
                    ),
                ),
                (
                    "remark",
                    models.TextField(blank=True, null=True, verbose_name="备注"),
                ),
            ],
            options={
                "verbose_name": "性别表",
                "verbose_name_plural": "性别表",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="Province",
            fields=[
                (
                    "code",
                    models.CharField(
                        max_length=2,
                        primary_key=True,
                        serialize=False,
                        verbose_name="省份代码",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="省份名称"
                    ),
                ),
                (
                    "short_name",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        unique=True,
                        verbose_name="简称",
                    ),
                ),
                (
                    "pinyin",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="拼音",
                    ),
                ),
            ],
            options={
                "verbose_name": "省份表",
                "verbose_name_plural": "省份表",
                "ordering": ("code",),
            },
        ),
        migrations.CreateModel(
            name="Title",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="职称名称"
                    ),
                ),
                (
                    "remark",
                    models.TextField(blank=True, null=True, verbose_name="备注"),
                ),
            ],
            options={
                "verbose_name": "职称表",
                "verbose_name_plural": "职称表",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="University",
            fields=[
                (
                    "code",
                    models.CharField(
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                        verbose_name="学校代码",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="学校名称"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="学校描述"),
                ),
                (
                    "province",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="commons.province",
                        verbose_name="所属省份",
                    ),
                ),
            ],
            options={
                "verbose_name": "学校表",
                "verbose_name_plural": "学校表",
                "ordering": ("code",),
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "code",
                    models.CharField(
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                        verbose_name="二级单位代码",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="二级单位名称"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="二级单位描述"
                    ),
                ),
                (
                    "primary_subjects",
                    models.ManyToManyField(
                        blank=True,
                        to="subjects.primarysubject",
                        verbose_name="拥有一级学科",
                    ),
                ),
                (
                    "secondary_subjects",
                    models.ManyToManyField(
                        blank=True,
                        to="subjects.secondarysubject",
                        verbose_name="拥有二级学科",
                    ),
                ),
                (
                    "university",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="commons.university",
                        verbose_name="所属学校",
                    ),
                ),
            ],
            options={
                "verbose_name": "二级单位表",
                "verbose_name_plural": "二级单位表",
                "ordering": ("code",),
                "unique_together": {("university", "name")},
            },
        ),
    ]
