# Generated by Django 5.2.3 on 2025-08-04 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("commons", "0001_initial"),
        ("subjects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Level",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="级别名称"
                    ),
                ),
                ("weight", models.FloatField(default=1.0, verbose_name="级别权重")),
                (
                    "remark",
                    models.TextField(blank=True, null=True, verbose_name="备注"),
                ),
            ],
            options={
                "verbose_name": "级别表",
                "verbose_name_plural": "级别表",
            },
        ),
        migrations.CreateModel(
            name="Indicator",
            fields=[
                (
                    "code",
                    models.CharField(
                        max_length=6,
                        primary_key=True,
                        serialize=False,
                        verbose_name="指标编码",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="指标名称"
                    ),
                ),
                ("weight", models.FloatField(default=1.0, verbose_name="指标权重")),
                (
                    "is_enable",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="指标描述"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="indicators.indicator",
                        verbose_name="父指标",
                    ),
                ),
            ],
            options={
                "verbose_name": "指标表",
                "verbose_name_plural": "指标表",
                "ordering": ("code",),
            },
        ),
        migrations.CreateModel(
            name="SubjectData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField(verbose_name="归属年份")),
                ("name", models.CharField(max_length=200, verbose_name="数据名称")),
                (
                    "value",
                    models.JSONField(blank=True, null=True, verbose_name="指标数据"),
                ),
                (
                    "remark",
                    models.TextField(blank=True, null=True, verbose_name="备注"),
                ),
                (
                    "created_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_time",
                    models.DateTimeField(auto_now=True, verbose_name="修改时间"),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="created_datas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
                (
                    "indicator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="indicators.indicator",
                        verbose_name="归属指标",
                    ),
                ),
                (
                    "level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="indicators.level",
                        verbose_name="归属级别",
                    ),
                ),
                (
                    "primary_subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="subjects.primarysubject",
                        verbose_name="归属一级学科",
                    ),
                ),
                (
                    "secondary_subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="subjects.secondarysubject",
                        verbose_name="归属二级学科",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.teacher",
                        verbose_name="主要负责人",
                    ),
                ),
                (
                    "university",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="commons.university",
                        verbose_name="归属学校",
                    ),
                ),
                (
                    "updator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="updated_datas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新者",
                    ),
                ),
            ],
            options={
                "verbose_name": "学科数据表",
                "verbose_name_plural": "学科数据表",
            },
        ),
    ]
