# Generated by Django 5.2.3 on 2025-08-06 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("indicators", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="level",
            options={
                "ordering": ("id",),
                "verbose_name": "级别表",
                "verbose_name_plural": "级别表",
            },
        ),
        migrations.AlterField(
            model_name="indicator",
            name="name",
            field=models.CharField(max_length=100, verbose_name="指标名称"),
        ),
    ]
