# Generated by Django 5.2.3 on 2025-08-14 15:13

import django.core.serializers.json
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_teacher_options_alter_user_options"),
        ("commons", "0001_initial"),
        ("indicators", "0002_alter_level_options_alter_indicator_name"),
        ("subjects", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subjectdata",
            options={
                "ordering": ("-created_time",),
                "verbose_name": "学科数据表",
                "verbose_name_plural": "学科数据表",
            },
        ),
        migrations.AlterField(
            model_name="subjectdata",
            name="indicator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="indicators.indicator",
                verbose_name="归属指标",
            ),
        ),
        migrations.AlterField(
            model_name="subjectdata",
            name="level",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="indicators.level",
                verbose_name="归属级别",
            ),
        ),
        migrations.AlterField(
            model_name="subjectdata",
            name="primary_subject",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="subjects.primarysubject",
                verbose_name="归属一级学科",
            ),
        ),
        migrations.AlterField(
            model_name="subjectdata",
            name="secondary_subject",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="subjects.secondarysubject",
                verbose_name="归属二级学科",
            ),
        ),
        migrations.AlterField(
            model_name="subjectdata",
            name="teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.teacher",
                verbose_name="主要负责人",
            ),
        ),
        migrations.AlterField(
            model_name="subjectdata",
            name="university",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="commons.university",
                verbose_name="归属学校",
            ),
        ),
        migrations.AlterField(
            model_name="subjectdata",
            name="value",
            field=models.JSONField(
                blank=True,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                null=True,
                verbose_name="指标数据",
            ),
        ),
    ]
