# Generated by Django 5.2.3 on 2026-01-14 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("indicators", "0003_alter_subjectdata_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subjectdata",
            name="authors",
            field=models.TextField(blank=True, null=True, verbose_name="参与者"),
        ),
        migrations.AddField(
            model_name="subjectdata",
            name="departments",
            field=models.TextField(blank=True, null=True, verbose_name="参与者单位"),
        ),
    ]
