# Generated by Django 5.2.3 on 2025-08-06 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("commons", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="university",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="commons.university",
                verbose_name="所属学校",
            ),
        ),
    ]
