# Generated by Django 5.2.3 on 2025-08-14 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_teacher_university"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="teacher",
            options={
                "ordering": ("id",),
                "verbose_name": "教师表",
                "verbose_name_plural": "教师表",
            },
        ),
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ("id",),
                "verbose_name": "用户表",
                "verbose_name_plural": "用户表",
            },
        ),
    ]
