# Generated by Django 5.2.3 on 2025-08-04 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PrimarySubject",
            fields=[
                (
                    "code",
                    models.CharField(
                        max_length=4,
                        primary_key=True,
                        serialize=False,
                        verbose_name="一级学科代码",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="一级学科名称")),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="一级学科描述"
                    ),
                ),
            ],
            options={
                "verbose_name": "一级学科",
                "verbose_name_plural": "一级学科",
                "ordering": ["category__code", "code"],
            },
        ),
        migrations.CreateModel(
            name="SubjectCategory",
            fields=[
                (
                    "code",
                    models.CharField(
                        max_length=2,
                        primary_key=True,
                        serialize=False,
                        verbose_name="门类代码",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="门类名称")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="门类描述"),
                ),
            ],
            options={
                "verbose_name": "学科门类",
                "verbose_name_plural": "学科门类",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="SecondarySubject",
            fields=[
                (
                    "code",
                    models.CharField(
                        max_length=6,
                        primary_key=True,
                        serialize=False,
                        verbose_name="二级学科代码",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="二级学科名称")),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="二级学科描述"
                    ),
                ),
                (
                    "primary_subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="secondary_subjects",
                        to="subjects.primarysubject",
                        verbose_name="所属一级学科",
                    ),
                ),
            ],
            options={
                "verbose_name": "二级学科",
                "verbose_name_plural": "二级学科",
                "ordering": [
                    "primary_subject__category__code",
                    "primary_subject__code",
                    "code",
                ],
            },
        ),
        migrations.AddField(
            model_name="primarysubject",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="primary_subjects",
                to="subjects.subjectcategory",
                verbose_name="所属门类",
            ),
        ),
    ]
